org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1
supported_version=26.1
archive_minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=26.0.0
release_type=beta
mod_id=snowrealmagic
maven_group=snownee.snowrealmagic
archives_base_name=SnowRealMagic

# Dependencies
fabric_api_version=0.144.1+26.1
cloth_config_version=19.0.147
# https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0-alpha.7
architectury_version=12.0.28
kiwi_version=26.0.2
rei_version=15.0.728
jade_version=26.0.4
iris_version=1.7.0+1.20.6
nightconfig_version=3.6.7