org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en
org.gradle.daemon=false

# NeoForge Properties
# check these on https://neoforged.net/
minecraft_version=26.1.2
supported_version=26.1.X
archive_minecraft_version=26.1
neo_version=26.1.2.93

# Mod Properties
mod_version=26.0.3
release_type=release
mod_id=snowrealmagic
maven_group=snownee.snowrealmagic
archives_base_name=SnowRealMagic

# Dependencies
forgified_fabric_api_version=0.155.0+26.1.2+3.4.2
cloth_config_version=26.1.154
# https://modrinth.com/mod/kiwi/versions
kiwi_version=26.0.17
rei_version=15.0.728
jade_version=26.1.8