org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1.2
supported_version=26.1.X
archive_minecraft_version=26.1
loader_version=0.18.6
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=26.0.2
release_type=release
mod_id=snowrealmagic
maven_group=snownee.snowrealmagic
archives_base_name=SnowRealMagic

# Dependencies
fabric_api_version=0.147.0+26.1.2
cloth_config_version=26.1.154
# https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0-alpha.8
architectury_version=12.0.28
kiwi_version=26.0.4
rei_version=15.0.728
jade_version=26.0.8
iris_version=1.7.0+1.20.6
nightconfig_version=3.6.7